### ISSUE TITLE
default config missing valuable entries

### ISSUE THREAD

**Issue by ozwaldorf** [hyprwm/Hypr#104]
**Please describe the bug**
the default config populated by hypr does not have the full range of things that it should for easy modifications

Ideally, the default config should be 1:1 with the example config provided in the repo

**Comment by ozwaldorf** [comment]
Figured out I needed
```
window_resize_speed=5 # This is for windows resizing
```

I'm going to refactor the issue to be related to the default config not having this value set

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hypr/blob/d1e83d16c27801ee59145056a2a104cd6ea3b910/example/hypr.conf#L59

?

**Comment by vaxerski** [comment]
fixed in af4641847b578b233a6f06806f575b3f320d74da
