### ISSUE TITLE
Dragging windows leaves trail and they do not disappear

### ISSUE THREAD

**Issue by weirdcease** [hyprwm/Hypr#106]
**Please describe the bug**
When I drag floating windows while using Hypr WM on Ubuntu, they leave a "trail" (see screenshot). Windows also do not disappear when I close them. I am using the default config and I built Hypr from source after installing all dependencies.

**Steps to reproduce:**
1. Build Hypr from source, following the instructions
2. Copy the binary and desktop file to the proper destinations
3. Copy `example/hypr.conf` to `~/.config/hypr/`
4. Install kitty, dmenu, etc
5. Reboot and select Hypr as the WM at login
6. Open new kitty window (or any other program)
7. Put window in floating mode with Super+Space
8. Press Super while dragging window, and it leaves a trail

**Expected behavior**
The window should drag and move properly, and then close when Super+C is pressed.

**Screenshots**
![2023-02-24-125256_1440x900_scrot](https://user-images.githubusercontent.com/78571139/221258766-7569564f-b799-4203-af9c-bddd3c15d0a7.png)

**Anything else?**
Sorry if this is a noob question or something that I am doing wrong. I made sure all dependencies are installed as well as G++. I have tried this on two different Ubuntu computers, with different GPUs, and the results are the same so I do not think this is driver-related.

**Log:**
There is no log at `/tmp/hypr/hypr.log` for some reason.

**Comment by vaxerski** [comment]
get a wallpaper utility.

**Comment by weirdcease** [comment]
Ok, it's working now with `feh`. Thanks.
