### ISSUE TITLE
Not able to compile Hypr

### ISSUE THREAD

**Issue by lucifer10607** [hyprwm/Hypr#108]
When i install it through the aur or make it from source my whole system crashes and it has only happened with this package til now

**Comment by vaxerski** [comment]
what are your system specs? maybe it's just running out of ram?

**Comment by lucifer10607** [comment]
well i actually try stuff on my old machine which has 2 gb ram but nothing has ever crashed building on it and also i install many things from the aur so can you tell me any alternate method to install the wm

**Comment by vaxerski** [comment]
there is no. C++ unfortunately is a bit resource hogging when compiling.

**Comment by lucifer10607** [comment]
well i was able to compile hyprland with the same machine but no problem and thanks for your response.
