### ISSUE TITLE
The top layer not used for waybar: it always goes to the bottom layer

### ISSUE THREAD

**Issue by csdvrx** [hyprwm/Hypr#112]
## waybar goes to the bottom layer

In waybar, I have:

    $ grep layer .config/waybar/*
    .config/waybar/config:    "layer": "top", // Waybar at top|bottom layer

**Expected behavior**

I would expect the waybar to be on the top layer, along with its tooltips, as it was configured that way.

**Problem**

However, I can't see the tooltips, and that's because `hyprctl layers` reports:

    Monitor eDP-1:
        Layer level 0 (background):
        Layer level 1 (bottom):
                Layer 55d09ee45270: xywh: 0 0 1440 25, namespace: waybar
        Layer level 2 (top):
        Layer level 3 (overlay):

**Anything else?**

I have no rules for layers in my hyprland configs except for blur:

    $ grep -E "layer|top|bottom" .config/hypr/*
    .config/hypr/hyprland.conf:layerrule = blur,^(waybar)$
    .config/hypr/hyprland.conf:layerrule = ignorezero,^(waybar)$
    .config/hypr/hyprland.conf:layerrule = blur,^(wofi)$

At least 1 other person has reported a similar issue

**Suggestion**

It might be interesting to add options to change the layers at runtime, so if waybar or anything is on the bottom layer like here, to move it to the top layer.

**Comment by vaxerski** [comment]
wrong fucking repo

**Comment by csdvrx** [comment]
Did you just glance at the first half to harshly conclude "work fucking repo"

Or did you make it to the conclusion and the suggestion that hyprland may benefit from an option to change the layers at runtime? (if that's possible)

**Comment by vaxerski** [comment]
This is not hyprland.
