### ISSUE TITLE
Keybindings Stop working after sometime of using the wm

### ISSUE THREAD

**Issue by lucifer10607** [hyprwm/Hypr#113]
First of all thanks for this great wm it is awesome but i have one problem that is the keybindings stop working after using only one app for sometime. After that if i open the window using the bar it opens fine but the binds do not work.

**Comment by vaxerski** [comment]
probably numlock? you can add numlock to ignore mod in the config

**Comment by lucifer10607** [comment]
Sorry i am not able to understand the issue can you explain please.
