### ISSUE TITLE
Touchpad config

### ISSUE THREAD

**Issue by ahmed-kaif** [hyprwm/Hypr#118]
**Is your feature request related to a problem? Please describe.**
I just installed Hypr on my laptop. I am using Pop_OS 22.04 LTS. My touchpad settings are messed up and it is pretty annoying to click and select. I managed to enable the natural scrolling with libinput but can't fix the tap settings. I saw some hyperland config where I can setup these settings in the config of hyperland.

**Describe the solution you'd like**
It would be great if you could add this kind of feature where I could easily configure my touchpad settings in the `hypr.conf `file.

**Anything else?**
A great wm indeed. I will be installing it soon in my desktop PC. Take love ❤️

**Comment by vaxerski** [comment]
hypr doesn't manage your devices, that's up to xorg.
