### ISSUE TITLE
Is Hypr a new X11 window manager? Can I use it?

### ISSUE THREAD

**Issue by jack9603301** [hyprwm/Hypr#119]
My computer has an Intel Iris xe graphics card, and I have always believed that Hyprland is the best window manager and synthesizer. However, due to some reasons, it has always had problems working on Wayland. I am working hard to make it work, but if everything is in vain, I may end up having to use an outdated x11 display server. Is it still actively developing and maintaining? I have seen i3wm, but due to being in Wayland, I prefer hyprland, which has a modern, beautiful interface and familiar usage habits. So in x 11, can I use it? Is it basically usable?

**Comment by vaxerski** [comment]
anything xorg-related is pretty much not very actively maintained

this window manager is not maintained anymore

**Comment by JustSimplyKyle** [comment]
Additionally, i3wm is actually xorg based
