### ISSUE TITLE
hyprctl Not Found in the Terminal

### ISSUE THREAD

**Issue by Neigdoig** [hyprwm/Hypr#122]
**Please describe the bug**
When I want to log out of Hypr, hyprctl is said to not exist, where it says `hypctl: command not found`. This behavior happens when built from source on Linux Mint 21.3 "Virginia" for me.

**Steps to reproduce:**
Open up a terminal, and type `hypctl dispatch exit 1`

**Expected behavior**
That command should be found, and it should log me out

**Screenshots**
N/A

**Anything else?**
As stated, it happens when built from source.

**Comment by vaxerski** [comment]
hyprctl is a hyprland thing, hypr doesn't have that.
