### ISSUE TITLE
Nothing in the Wiki about logging out

### ISSUE THREAD

**Issue by Neigdoig** [hyprwm/Hypr#123]
My apologies about this, especially in Issue #122, for I am very new to Hypr.

I'm making my configuration use the same hotkeys and keychords as i3 (my main WM), but I don't see anything in the documentation about logging out of Hypr. I'm still learning, so please bear with me on that.

Is there a command one could give to Hypr to log out of it? If not, is it possible for this to happen in the future?

**Comment by vaxerski** [comment]
`killall Xorg`?

**Comment by Neigdoig** [comment]
I'll take a look once I have time.

**Comment by vaxerski** [comment]
where?

**Comment by Neigdoig** [comment]
In my `hypr.conf` file, I went ahead and added `bind=SUPERSHIFT,Q,exec,echo {PASSWORD} | sudo -S killall Xorg`. Otherwise, if you're talking about something else (or somewhere else), let me know.

**Comment by vaxerski** [comment]
I meant where do you want it put in the wiki

**Comment by Neigdoig** [comment]
I'd say probably under Configuring Hypr would be the best bet. The specific subsection, that I leave to you.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hypr/assets/43317083/c53d923c-77cd-4b0f-8d57-2e0d25f7f2e1)
already there tho reading it

**Comment by Neigdoig** [comment]
Huh, maybe clarify that underneath it as a backup for if it doesn't work.

**Comment by vaxerski** [comment]
added
