### ISSUE TITLE
Possible to make a new release?

### ISSUE THREAD

**Issue by barracuda156** [hyprwm/Hypr#127]
The code has changed significantly since the last release (tag) from 2022. Could we make a new one?

P. S. Some Macports folks dislike commit-based ports, and I cannot use a tag, because that one is broken due to https://github.com/hyprwm/Hypr/issues/125#issue-2203960802

**Comment by vaxerski** [comment]
enjoy https://github.com/hyprwm/Hypr/releases/tag/1.1.4

**Comment by barracuda156** [comment]
Thank you!
