### ISSUE TITLE
Keyboard Layout Configuration and Switching 

### ISSUE THREAD

**Issue by MrC-101** [hyprwm/Hypr#128]
Is it possible to add more than one keyboard layout and a switching configuration between them in hypr.conf? Thanks in advance!

**Comment by vaxerski** [comment]
isn't that handled by xorg?

**Comment by MrC-101** [comment]
I'm on Arcolinux and tried with localectl command already 
`localectl --no-convert set-x11-keymap us,gr pc104 grp:caps_toggle`
and manually as well, but I'm stuck with us only. What am I missing? Thanks in advance!

**Comment by vaxerski** [comment]
no clue, havent used X in over 2 years

**Comment by MrC-101** [comment]
Ohh, ok no worries. I'll try to figure it out somehow. Thank you for ur work with hypr anyway! Very much appreciated! Cheers!

**Comment by v1ctorio** [comment]
> Ohh, ok no worries. I'll try to figure it out somehow. Thank you for ur work with hypr anyway! Very much appreciated! Cheers!

I don't know if I'm missing something but aren't you referring to this? https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts

Then you change it with hyprctl and that's it no? https://wiki.hyprland.org/Configuring/Using-hyprctl/#switchxkblayout

**Comment by MrC-101** [comment]
> I don't know if I'm missing something but aren't you referring to this? https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts

That's for hyprland. I'm using the hyprwm under X11, so I change the xorg config file (00-keyboard.conf)


> Then you change it with hyprctl and that's it no? https://wiki.hyprland.org/Configuring/Using-hyprctl/#switchxkblayout

I was hoping to be able to change through different keyboard layouts using a key or a combination of keys on the keyboard ie. capslock or alt-shift combo

**Comment by v1ctorio** [comment]
Oh I'm so sorry, I didn't realize this was hypr repo.

Setting a key combo is just setting a keybind in ur hypr config to execute the necessary command no? 


https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration
https://man7.org/linux/man-pages/man1/localectl.1.html
https://github.com/hyprwm/Hypr/wiki/Configuring-Hypr#binds
https://forum.endeavouros.com/t/cannot-set-keyboard-layout-with-localectl/40233


https://www.x.org/releases/X11R7.5/doc/input/XKB-Config.html

What's ur current keyboard.conf?

**Comment by MrC-101** [comment]
> Oh I'm so sorry, I didn't realize this was hypr repo.

No worries! I was getting confused too!

> Setting a key combo is just setting a keybind in ur hypr config to execute the necessary command no?

No, that's why I asked if that would be possible to be implemented.
 
> What's ur current keyboard.conf?

current 00-keyboard.conf

```
Section "InputClass"
              Identifier "system-keyboard"
              MatchIsKeyboard "on"
              Option "XkbLayout" "us,gr"
              Option "XkbOptions" "grp:alt_shift_toggle"
 EndSection
```

**Comment by MrC-101** [comment]
Couldn't find a solution so I installed hyprland and managed to control keyboard layout from its conf file. Thanks everyone for trying to help. Closing this. Best regards.
