### ISSUE TITLE
Can we get tabbed windows?

### ISSUE THREAD

**Issue by IamDaedalus** [hyprwm/Hypr#85]
Hi
I discovered Hypr today and I'm still figuring it out but so far I am loving the experience. Coming from i3, I noticed there's no support for tabbed windows in Hypr which is usually how I work on my PC. Is there already some support that I'm not aware of or is it yet to be implemented?

Thanks

**Comment by vaxerski** [comment]
no, if you want tabbed windows, move to hyprland.

**Comment by IamDaedalus** [comment]
Setup Hyprland some hours ago and I'm having more problems than with Hypr
I'll test some more before opening an issue over there thanks
