### ISSUE TITLE
Installed over KDE - Buggy behaviour

### ISSUE THREAD

**Issue by RandomLegend** [hyprwm/Hypr#87]
**Please describe the bug**
I installed Hypr on a new User on Garuda Linux with KDE Plasma as basis. I took the example config, modified the keybinds to my liking and switched to Hypr in SDDM.

Some bugs at the beginning:
1) Resolution is wrong; I have a 3440x1440 monitor but it defaults to 1920x1080
2) QT theme from Kvantum is not applied
3) Refreshrate cannot go higher than 60 even though my monitor has 144

After i start for example kate, the resolution automatically corrects itself to 3440x1440 but now all my keybindings don't work. And my superkey will not be recognized anymore at all.

I intentionally tested this with a new user to check if any of my installed programs mess with Hypr.

**Comment by vaxerski** [comment]
Hypr doesn't control your resolution - Xorg does.

The QT theme is not controlled by Hypr. It's controlled by configs.

Refresh rate - if you mean the monitor's, that is not controlled by Hypr, but by Xorg. If you mean the animations', then max_fps is your friend.

**Comment by RandomLegend** [comment]
1) Xorg config is set to 3440x1440@144 - intial start with hypr goes into 1920x1080@60 after start of kate it goes to correct configuration - how comes?
2) The main bug is that my superkey doesn't get recognized after i start kate

In my opinion this issue is not closed. Especially since the main bug (breakage of keybinding) was not even acknoledged by you
