### ISSUE TITLE
Build instructions for opensuse tumblweed

### ISSUE THREAD

**Issue by kylian-002** [hyprwm/Hypr#88]
**Is your feature request related to a problem? Please describe.**
Missing build instructions for openSUSE tumbleweed. Almost the same as fedora but some packages have a slightly different name.

**Describe the solution you'd like**
adding this to the build instructions shut help.

`sudo zypper install gcc-c++ ninja cmake gcc cairo-devel glib2-devel gtkmm3-devel harfbuzz-devel libxcb-devel libX11-xcb1 xcb-util-wm-devel xcb-util-wm-devel xcb-util-cursor-devel xcb-util-cursor-devel xcb-util-keysyms-devel xcb-util-keysyms-devel libxcb-devel libxcb-devel xcb-util-devel
`

**Anything else?**

**Comment by vaxerski** [comment]
done
