### ISSUE TITLE
Keybindings from hypr.conf not working

### ISSUE THREAD

**Issue by arcolinuxz** [hyprwm/Hypr#89]
**Please describe the bug**

any key in our hypr.conf is not working

https://github.com/arcolinux/arcolinux-hypr/blob/c4bfb2517c9bc259152db167b0005e973a7d8aa8/etc/skel/.config/hypr/hypr.conf#L73

any key in sxhkd is working
https://github.com/arcolinux/arcolinux-hypr/tree/main/etc/skel/.config/hypr/sxhkd

**Steps to reproduce:**
Install our app package on ArcoLinux

Package is renamed to hypr-dev-git (same from AUR - named there hypr-git added xorg-xmodmap as dependency) 
Using a different naming convention to keep track of your commits to github
r369.3e3d943-2 - commit 369 at the moment
https://github.com/arcolinux/arcolinux_repo_3party/blob/main/x86_64/hypr-dev-git-r369.3e3d943-2-x86_64.pkg.tar.zst

Install our config package on ArcoLinux

https://github.com/arcolinux/arcolinux_repo/blob/main/x86_64/arcolinux-hypr-git-22.11-06-any.pkg.tar.zst
https://github.com/arcolinux/arcolinux-hypr

**Expected behavior**
We would like to be able to use the keybindings particularly quit an application: super + Q 

**Video**
3 issues

1. keybindings (quit application for example)
2. ewmh on polybar
3. system panel icons not responding on a click

https://youtu.be/s84yLa80BFc

**Image**

![hypr-issues](https://user-images.githubusercontent.com/36679406/202116295-cfd8b1ee-2483-4f25-bf6f-2ae59b1d9f6e.png)

**Log:**
Please attach a log. (paste it into pastebin and paste here the url) The log can be found in a temp file located in /tmp/hypr/hypr.log.

[hypr.log](https://github.com/hyprwm/Hypr/files/10019058/hypr.log)

**Comment by vaxerski** [comment]
usually means another mod is active, like scroll lock / num lock / caps lock. 

To avoid num lock blocking your keybinds, use ignore_mod

**Comment by arcolinuxz** [comment]
It was the num lock

ignore=num_lock added to hypr.conf

**Comment by arcolinuxz** [comment]
I thought I had solved it but ...

if I set num lock off - it all works
but
If I set num lock on again - it does not work

checked the name with  `xev -event keyboard`
and it does read as 

`KeyRelease event, serial 28, synthetic NO, window 0x6c00001,
    root 0x1d9, subw 0x0, time 5934248, (472,250), root:(1438,796),
    state 0x10, keycode 77 (keysym 0xff7f, Num_Lock), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False`

so added the line

`ignore_mod=Num_Lock`

 with capital letters

still no luck

**Comment by arcolinuxz** [comment]
testing LOCK now

**Comment by arcolinuxz** [comment]
ignore_mod=LOCK is not working

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/202182871-c573c6f6-6968-42fc-ab96-b08f9a95a09d.png)
try one of the MODx ones. Don't have a keyboard with a numlock rn.

**Comment by arcolinuxz** [comment]
testing

**Comment by arcolinuxz** [comment]
MOD2 is numlock for me

**Comment by arcolinuxz** [comment]
Retested on other systems

that was the solution
maybe add the line in the example config with a # in front

thanks for the help

one issue down
