### ISSUE TITLE
Workspaces - background color is green

### ISSUE THREAD

**Issue by arcolinuxz** [hyprwm/Hypr#94]
Can we change the green background color?

![green](https://user-images.githubusercontent.com/36679406/202232079-889e557d-e112-49b4-a9a8-07ab42935249.png)

I thought it would be this code

module=left,X,0xff8000ff,0xffffffff,1,workspaces

When I remove the line - I no longer see the workspaces 
but if I change the colors nothing changes?
Can we change colors for active and non active workspaces?
+
Is it possible to click on the workspaces and then change to the workspace?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/202250024-5dea8963-b85f-426b-b0e4-467863e8e4a8.png)

> Is it possible to click on the workspaces and then change to the workspace?

No

**Comment by arcolinuxz** [comment]
OMG - sorry for that
Looked over it completely
and how can we change the font color of the active workspace?
![black](https://user-images.githubusercontent.com/36679406/202251249-526fb707-fb0b-4e92-ae6a-dd26989394e1.png)

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/202252536-82e3c9b3-faec-4c8e-9c1d-3750543e4ba1.png)
done

**Comment by arcolinuxz** [comment]
I am probably too fast

![error](https://user-images.githubusercontent.com/36679406/202262636-1b01261d-9157-41fd-a8ca-c13972850470.png)

based on last commit 371

**Comment by vaxerski** [comment]
you prolly arent on 371 my best guess

**Comment by arcolinuxz** [comment]
I have rebuilt the package and now it is alright. 
Closing this topic
![image](https://user-images.githubusercontent.com/36679406/202712519-c7c2bf6d-d557-46e3-af4d-e3c88386e5d5.png)
